# Generated by Django 5.1.6 on 2026-02-19 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindashboard', '0003_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('time_added', models.TimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('UNAVAILABLE', 'Unavailable')], default='AVAILABLE', max_length=15)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_entries', to='admindashboard.item')),
            ],
            options={
                'db_table': 'menu',
            },
        ),
    ]
