# Generated by Django 5.1.6 on 2026-02-19 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_wallet'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
    ]
