# Generated by Django 5.1.6 on 2026-02-21 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindashboard', '0004_menu'),
        ('student', '0004_order_rejected_reason_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_orders', to='admindashboard.user'),
        ),
    ]
