# Generated by Django 5.1.6 on 2026-02-21 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='transaction_type',
            field=models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit'), ('RETURN', 'Return')], max_length=6),
        ),
    ]
